/*
 * JS for mainGamePage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'bde7dfdc-512d-4b9e-8c82-d8d87e3e9c86';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "insideCM",
    "location": "insideCM.html"
}, {
    "name": "mainGamePage",
    "location": "mainGamePage.html"
}, {
    "name": "mainGamePage_clone_1",
    "location": "mainGamePage_clone_1.html"
}];

function mainGamePage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'moveUp': 'mainGamePage_moveUp',
        'moveDown': 'mainGamePage_moveDown',
        'moveLeft': 'mainGamePage_moveLeft',
        'moveRight': 'mainGamePage_moveRight',
        'mobilelabel_8': 'mainGamePage_mobilelabel_8',
        'mobilegrid_9': 'mainGamePage_mobilegrid_9',
        'mobilegridcell_10': 'mainGamePage_mobilegridcell_10',
        'man': 'mainGamePage_man',
        'mobilegridcell_11': 'mainGamePage_mobilegridcell_11',
        'mobilegridcell_30': 'mainGamePage_mobilegridcell_30',
        'mobilegridcell_31': 'mainGamePage_mobilegridcell_31',
        'mobilegridcell_32': 'mainGamePage_mobilegridcell_32',
        'mobilegridcell_33': 'mainGamePage_mobilegridcell_33',
        'mobilegridcell_34': 'mainGamePage_mobilegridcell_34',
        'mobilegridcell_35': 'mainGamePage_mobilegridcell_35',
        'mobilegridcell_36': 'mainGamePage_mobilegridcell_36',
        'mobilegridcell_37': 'mainGamePage_mobilegridcell_37',
        'mobilegridcell_12': 'mainGamePage_mobilegridcell_12',
        'mobilegridcell_13': 'mainGamePage_mobilegridcell_13',
        'mobilegridcell_38': 'mainGamePage_mobilegridcell_38',
        'mobilegridcell_39': 'mainGamePage_mobilegridcell_39',
        'mobilegridcell_40': 'mainGamePage_mobilegridcell_40',
        'mobilegridcell_41': 'mainGamePage_mobilegridcell_41',
        'mobilegridcell_42': 'mainGamePage_mobilegridcell_42',
        'mobilegridcell_43': 'mainGamePage_mobilegridcell_43',
        'mobilegridcell_44': 'mainGamePage_mobilegridcell_44',
        'mobilegridcell_45': 'mainGamePage_mobilegridcell_45',
        'mobilegridcell_14': 'mainGamePage_mobilegridcell_14',
        'mobilegridcell_15': 'mainGamePage_mobilegridcell_15',
        'mobilegridcell_46': 'mainGamePage_mobilegridcell_46',
        'mobilegridcell_47': 'mainGamePage_mobilegridcell_47',
        'mobilegridcell_48': 'mainGamePage_mobilegridcell_48',
        'mobilegridcell_49': 'mainGamePage_mobilegridcell_49',
        'CMstore': 'mainGamePage_CMstore',
        'mobilegridcell_50': 'mainGamePage_mobilegridcell_50',
        'mobilegridcell_51': 'mainGamePage_mobilegridcell_51',
        'mobilegridcell_52': 'mainGamePage_mobilegridcell_52',
        'mobilegridcell_53': 'mainGamePage_mobilegridcell_53',
        'mobilegridcell_16': 'mainGamePage_mobilegridcell_16',
        'mobilegridcell_17': 'mainGamePage_mobilegridcell_17',
        'mobilegridcell_54': 'mainGamePage_mobilegridcell_54',
        'mobilegridcell_55': 'mainGamePage_mobilegridcell_55',
        'mobilegridcell_56': 'mainGamePage_mobilegridcell_56',
        'mobilegridcell_57': 'mainGamePage_mobilegridcell_57',
        'mobilegridcell_58': 'mainGamePage_mobilegridcell_58',
        'mobilegridcell_59': 'mainGamePage_mobilegridcell_59',
        'mobilegridcell_60': 'mainGamePage_mobilegridcell_60',
        'mobilegridcell_61': 'mainGamePage_mobilegridcell_61',
        'mobilegridcell_18': 'mainGamePage_mobilegridcell_18',
        'mobilegridcell_19': 'mainGamePage_mobilegridcell_19',
        'mobilegridcell_62': 'mainGamePage_mobilegridcell_62',
        'mobilegridcell_63': 'mainGamePage_mobilegridcell_63',
        'mobilegridcell_64': 'mainGamePage_mobilegridcell_64',
        'mobilegridcell_65': 'mainGamePage_mobilegridcell_65',
        'mobilegridcell_66': 'mainGamePage_mobilegridcell_66',
        'mobilegridcell_67': 'mainGamePage_mobilegridcell_67',
        'mobilegridcell_68': 'mainGamePage_mobilegridcell_68',
        'mobilegridcell_69': 'mainGamePage_mobilegridcell_69',
        'mobilegridcell_20': 'mainGamePage_mobilegridcell_20',
        'mobilegridcell_21': 'mainGamePage_mobilegridcell_21',
        'mobilegridcell_70': 'mainGamePage_mobilegridcell_70',
        'mobilegridcell_71': 'mainGamePage_mobilegridcell_71',
        'mobilegridcell_72': 'mainGamePage_mobilegridcell_72',
        'mobilegridcell_73': 'mainGamePage_mobilegridcell_73',
        'mobilegridcell_74': 'mainGamePage_mobilegridcell_74',
        'mobilegridcell_75': 'mainGamePage_mobilegridcell_75',
        'mobilegridcell_76': 'mainGamePage_mobilegridcell_76',
        'mobilegridcell_77': 'mainGamePage_mobilegridcell_77',
        'mobilegridcell_22': 'mainGamePage_mobilegridcell_22',
        'mobilegridcell_23': 'mainGamePage_mobilegridcell_23',
        'mobilegridcell_78': 'mainGamePage_mobilegridcell_78',
        'mobilegridcell_79': 'mainGamePage_mobilegridcell_79',
        'mobilegridcell_80': 'mainGamePage_mobilegridcell_80',
        'mobilegridcell_81': 'mainGamePage_mobilegridcell_81',
        'mobilegridcell_82': 'mainGamePage_mobilegridcell_82',
        'mobilegridcell_83': 'mainGamePage_mobilegridcell_83',
        'mobilegridcell_84': 'mainGamePage_mobilegridcell_84',
        'mobilegridcell_85': 'mainGamePage_mobilegridcell_85',
        'mobilegridcell_24': 'mainGamePage_mobilegridcell_24',
        'mobilegridcell_25': 'mainGamePage_mobilegridcell_25',
        'mobilegridcell_86': 'mainGamePage_mobilegridcell_86',
        'mobilegridcell_87': 'mainGamePage_mobilegridcell_87',
        'mobilegridcell_88': 'mainGamePage_mobilegridcell_88',
        'mobilegridcell_89': 'mainGamePage_mobilegridcell_89',
        'mobilegridcell_90': 'mainGamePage_mobilegridcell_90',
        'mobilegridcell_91': 'mainGamePage_mobilegridcell_91',
        'mobilegridcell_92': 'mainGamePage_mobilegridcell_92',
        'mobilegridcell_93': 'mainGamePage_mobilegridcell_93',
        'mobilegridcell_26': 'mainGamePage_mobilegridcell_26',
        'mobilegridcell_27': 'mainGamePage_mobilegridcell_27',
        'mobilegridcell_94': 'mainGamePage_mobilegridcell_94',
        'mobilegridcell_95': 'mainGamePage_mobilegridcell_95',
        'mobilegridcell_96': 'mainGamePage_mobilegridcell_96',
        'mobilegridcell_97': 'mainGamePage_mobilegridcell_97',
        'mobilegridcell_98': 'mainGamePage_mobilegridcell_98',
        'mobilegridcell_99': 'mainGamePage_mobilegridcell_99',
        'mobilegridcell_100': 'mainGamePage_mobilegridcell_100',
        'mobilegridcell_101': 'mainGamePage_mobilegridcell_101',
        'mobilegridcell_28': 'mainGamePage_mobilegridcell_28',
        'mobilegridcell_29': 'mainGamePage_mobilegridcell_29',
        'mobilegridcell_102': 'mainGamePage_mobilegridcell_102',
        'mobilegridcell_103': 'mainGamePage_mobilegridcell_103',
        'mobilegridcell_104': 'mainGamePage_mobilegridcell_104',
        'mobilegridcell_105': 'mainGamePage_mobilegridcell_105',
        'mobilegridcell_106': 'mainGamePage_mobilegridcell_106',
        'mobilegridcell_107': 'mainGamePage_mobilegridcell_107',
        'mobilegridcell_108': 'mainGamePage_mobilegridcell_108',
        'mobilegridcell_109': 'mainGamePage_mobilegridcell_109'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'mainGamePage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var mainGamePage_onLoad = function() {
            mainGamePage_elementsExtraJS();

            setAttribute_('mainGamePage_man', 'style', '\"position: relative; left: 0px; top: 0px;\"');
            $('[id="mainGamePage_man"]').refresh();

            mainGamePage_deviceEvents();
            mainGamePage_windowEvents();
            mainGamePage_elementsEvents();
        };

    // screen window events


    function mainGamePage_windowEvents() {

        $('#mainGamePage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#mainGamePage').on({
            pageshow: function(event) {
                Appery.storage.xCoord.set(0);
                Appery.storage.yCoord.set(0);
            },
        });

    };

    // device events


    function mainGamePage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function mainGamePage_elementsExtraJS() {
        // screen (mainGamePage) extra code

    };

    // screen elements handler


    function mainGamePage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#mainGamePage_mobilecontainer [name="moveUp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var temp = Appery.storage.yCoord.get();
                    var temp2 = Appery.storage.xCoord.get();

                    if ((temp2 === 175) && (temp === 150)) {

                        Apperyio.navigateTo('mainGamePage_clone_1', {
                            transition: 'slideup',
                            reverse: false
                        });

                    }
                    if (parseInt(temp) !== 0) {
                        moveUp(temp, document.getElementById("mainGamePage_man"));
                    };

                }
            },
        }, '#mainGamePage_mobilecontainer [name="moveUp"]');
        $(document).off("click", '#mainGamePage_mobilecontainer [name="moveDown"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var temp = Appery.storage.yCoord.get();
                    if (parseInt(temp) !== 250) {
                        moveDown(temp, document.getElementById("mainGamePage_man"));
                    };

                }
            },
        }, '#mainGamePage_mobilecontainer [name="moveDown"]');
        $(document).off("click", '#mainGamePage_mobilecontainer [name="moveLeft"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var temp = Appery.storage.xCoord.get();
                    if (parseInt(temp) !== 0) {
                        moveLeft(temp, document.getElementById("mainGamePage_man"));
                    };

                }
            },
        }, '#mainGamePage_mobilecontainer [name="moveLeft"]');
        $(document).off("click", '#mainGamePage_mobilecontainer [name="moveRight"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var temp = Appery.storage.xCoord.get();
                    if (parseInt(temp) !== 250) {
                        moveRight(temp, document.getElementById("mainGamePage_man"));
                    };

                }
            },
        }, '#mainGamePage_mobilecontainer [name="moveRight"]');

    };

    $(document).off("pagebeforeshow", "#mainGamePage").on("pagebeforeshow", "#mainGamePage", function(event, ui) {
        Apperyio.CurrentScreen = "mainGamePage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    mainGamePage_onLoad();
};

$(document).off("pagecreate", "#mainGamePage").on("pagecreate", "#mainGamePage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    mainGamePage_js();
});